---
- hosts: cyber_range
  become: true
  roles:
    - cyber_range_setup
    - logging

- hosts: trainee_workstations
  become: true
  roles:
    - bips
    - logging

- hosts: training_platform
  become: true
  roles:
    - cicms

- hosts: soc_server
  become: true
  roles:
    - ng_siem
    - ng_soar
