---
- hosts: infected-host
  become: yes
  roles:
    - infected-host

- hosts: c2-server
  become: yes
  roles:
    - c2-server

- hosts: soc-server
  become: yes
  roles:
    - soc-server

- hosts: cti-component
  become: yes
  roles:
    - cti-component
