---
- hosts: infected-host
  become: yes
  roles:
    - infected_host

- hosts: c2-server
  become: yes
  roles:
    - c2_server

- hosts: soc-server
  become: yes
  roles:
    - soc_server

- hosts: cti-component
  become: yes
  roles:
    - cti_component
